version: '3.9'

services:

  owncloud_user1:
    image: owncloud/server:latest
    container_name: owncloud_user1
    ports:
      - "8081:8080"
    depends_on:
      - postgres_user1
      - redis_user1
    environment:
      - OWNCLOUD_DB_TYPE=pgsql
      - OWNCLOUD_DB_NAME=owncloud_user1
      - OWNCLOUD_DB_USERNAME=user1
      - OWNCLOUD_DB_PASSWORD=password1
      - OWNCLOUD_DB_HOST=postgres_user1
      - OWNCLOUD_REDIS_HOST=redis_user1
      - OWNCLOUD_ADMIN_USERNAME=admin_user1
      - OWNCLOUD_ADMIN_PASSWORD=adminpassword1
    volumes:
      - owncloud_data_user1:/mnt/data
    restart: always

  postgres_user1:
    image: postgres:15
    container_name: postgres_user1
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: owncloud_user1
    volumes:
      - postgres_data_user1:/var/lib/postgresql/data
    restart: always

  redis_user1:
    image: redis:7
    container_name: redis_user1
    command: ["redis-server", "--requirepass", "redispassword1"]
    environment:
      - REDIS_PASSWORD=redispassword1
    volumes:
      - redis_data_user1:/data
    restart: always

  owncloud_user2:
    image: owncloud/server:latest
    container_name: owncloud_user2
    ports:
      - "8082:8080"
    depends_on:
      - postgres_user2
      - redis_user2
    environment:
      - OWNCLOUD_DB_TYPE=pgsql
      - OWNCLOUD_DB_NAME=owncloud_user2
      - OWNCLOUD_DB_USERNAME=user2
      - OWNCLOUD_DB_PASSWORD=password2
      - OWNCLOUD_DB_HOST=postgres_user2
      - OWNCLOUD_REDIS_HOST=redis_user2
      - OWNCLOUD_ADMIN_USERNAME=admin_user2
      - OWNCLOUD_ADMIN_PASSWORD=adminpassword2
    volumes:
      - owncloud_data_user2:/mnt/data
    restart: always

  postgres_user2:
    image: postgres:15
    container_name: postgres_user2
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: owncloud_user2
    volumes:
      - postgres_data_user2:/var/lib/postgresql/data
    restart: always

  redis_user2:
    image: redis:7
    container_name: redis_user2
    command: ["redis-server", "--requirepass", "redispassword2"]
    environment:
      - REDIS_PASSWORD=redispassword2
    volumes:
      - redis_data_user2:/data
    restart: always

volumes:
  owncloud_data_user1:
  postgres_data_user1:
  redis_data_user1:
  owncloud_data_user2:
  postgres_data_user2:
  redis_data_user2:
